# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce58322530eebce92187bd8802c40698cf61ba8c5adb2b54e068b35a6595552755c6e7b8a33607322d73e798f838ee142ac8124522d9662718a739753584c487

test:
  secret_key_base: bab29aece18c41c2b7cb5f672adc3ed83eb5d5d2e7b595a06a684ca4d1347d150808cc209ef6bd12bf8686e3d01e8b18acf7d9004bf714563085abfbbf2a1b98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
